version: '3.8'

services:
  # PetStore API Test Runner
  petstore-api-tests:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: petstore-api-test-runner
    environment:
      - TEST_ENVIRONMENT=docker
      - BASE_URL=https://petstore.swagger.io/v2
      - PARALLEL_THREADS=4
      - REPORT_PATH=/app/target/reports
    volumes:
      - ./target/reports:/app/target/reports
      - ./target/logs:/app/target/logs
      - ./target/screenshots:/app/target/screenshots
      - ./target/allure-results:/app/target/allure-results
    networks:
      - test-network
    depends_on:
      - mongodb
    command: ["mvn", "clean", "test", "-Dtest=Regression Tests"]
    restart: unless-stopped

  # MongoDB Database for test data
  mongodb:
    image: mongo:6.0
    container_name: petstore-test-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
      MONGO_INITDB_DATABASE: petstore_test
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./database/mongodb/init.js:/docker-entrypoint-initdb.d/init.js:ro
    networks:
      - test-network
    restart: unless-stopped

  # Allure Report Server
  allure:
    image: frankescobar/allure-docker-service
    container_name: petstore-test-allure
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 1
      KEEP_HISTORY: 1
    ports:
      - "5050:5050"
    volumes:
      - ./target/allure-results:/app/allure-results
      - ./target/allure-report:/app/default-reports-portal
    networks:
      - test-network
    restart: unless-stopped

volumes:
  mongodb_data:

networks:
  test-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16 