version: '3.8'

services:
  # PetStore API Test Runner
  petstore-api-tests:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: petstore-api-test-runner
    environment:
      - TEST_ENVIRONMENT=docker
      - BASE_URL=https://petstore.swagger.io/v2
      - PARALLEL_THREADS=4
      - REPORT_PATH=/app/target/reports
    volumes:
      - ./target:/app/target
    networks:
      - test-network
    command: ["mvn", "clean", "test", "-Dtest=Regression Tests"]
    restart: unless-stopped

  # MongoDB Database for test data
  mongodb:
    image: mongo:6.0
    container_name: petstore-test-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
      MONGO_INITDB_DATABASE: petstore_test
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
      - ./database/mongodb/init.js:/docker-entrypoint-initdb.d/init.js:ro
    networks:
      - test-network
    restart: unless-stopped



volumes:
  mongodb_data:

networks:
  test-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16 